modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="observer"
version="0.1.0"
displayName="Observer"
authors="koukebu"
description='''Minimal observer for interface analysis on Forge 1.20.1.'''

[[dependencies.observer]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.observer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"